### ISSUE TITLE
How to run testing?

### ISSUE THREAD

**Issue by cwh1981** [roseperrone/video-object-detection#2]
when I run below command, it is not working with some error.
command:
"python main.py --model=original_train_val.prototxt"

error:
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    test_detector_on_eggs()
  File "main.py", line 92, in test_detector_on_eggs
    draw_noun_detections_one_video_frames(video_id, 'n07840804')
  File "main.py", line 66, in draw_noun_detections_on_video_frames
    annotated_dir = join(dirname(dirname(MODELS[FLAGS.model][0])),
KeyError: 'original_train_val.prototxt'

Can you explain how to run example?
thank you for your help

Marx HA

**Comment by preksha12** [comment]
Is your prepare_data.py working ?In my case it is working but it is not generating image_mean_binaryproto file .So what should be the solution?
