### ISSUE TITLE
unable to filter images

### ISSUE THREAD

**Issue by Atul997** [roseperrone/video-object-detection#4]
hi 
when i am running **filter_images.py** from terminal -
`python filter_positive_images.py --src /home/admin1/video-object-detection-master/data/imagenet/n07840804/images --dst /home/admin1/video-object-detection-master/data/imagenet/n07840804/pos`

it throws error- 
Traceback (most recent call last):
  File "filter_positive_images.py", line 47, in <module>
    show_image(filename)
  File "filter_positive_images.py", line 31, in show_image
    img = pygame.image.load(filename)
pygame.error: Unsupported image format

I also checked for images in folder which didn't download correctly and deleted them.
How can i overcome this error?

**Comment by ghost** [comment]
No idea. But I wonder why did she wanted to localize eggs so badly. . Maybe what could be done is just try to see the false classifications with unmodified neural net, and then create a second net which does classification on top of first if the category provided by first falls in the suspicious classes.
